let a = 1;
print("test"+a);
a += 1;
print("test"+a);
// 函数创建
func printWrapper(text) {
    print("warpper"+text);
}
printWrapper(a);
// 数组操作
let array = [1,2,3,a];
array[1] = 6;
append(array,72);
let i = 0;
while(i < len(array)) {
    printWrapper(array[i]);
    i+=1;
}

func Closure() {
    // 闭包
    let value = 0;
    func add(input) {
        if (input) {
            value += input;
        } else {
            value += 1;
        }
        
        print("Closure value:" + value);
        print("Current time:" + time());
        return value;
    }
    return add;
}
let add = Closure();
add();
add();
add(3);
add(null);

// 异步回调
setTimeout(1000,func cb(){
    print("one");
    input("input:",func ret(answer) {
        print("output:"+answer + rand());
    });
});